### PR TITLE
Check coding style

### PR DESCRIPTION
**Pull request by szepeviktor**
This PR stops PRs violating coding standard defined in `.php_cs`

Please fix coding style `./bin/php-cs-fixer fix` **before** merging.

### CODE REVIEW

**Comment by stelin** [comment]
@szepeviktor Thank for your contributing!

**Comment by inhere** [comment]
@szepeviktor  Thank you very much! 

Welcome to join the [gitter](https://gitter.im/swoft-cloud/community) community to participate in discussions and sharing.

**Comment by inhere** [comment]
@szepeviktor  I have restored the phpstan script.

https://github.com/swoft-cloud/swoft/commit/283ee7663e000cd995b75876245f9749999d70e0

**Comment by szepeviktor** [comment]
You're welcome.

I am not using projects I contribute to :)

I promote phpstan and randomly contributing.

**Comment by inhere** [comment]
@szepeviktor  OK, but still very grateful for your contribution

**Pull request merged**
