### PR TITLE
Follow changes in swoole-ide-helper

### PR DESCRIPTION
**Pull request by szepeviktor**
@inhere /src -> /output

### CODE REVIEW

**Comment by szepeviktor** [comment]
We've got results! https://travis-ci.org/swoft-cloud/swoft/jobs/584856059#L1036

I am not able to comprehend errors :)

> Call to an undefined method Swoft\Session\SessionInterface::push()

**Comment by szepeviktor** [comment]
You can also dig into initially ignored ones https://github.com/swoft-cloud/swoft/blob/master/phpstan.neon.dist#L17-L53

**Comment by inhere** [comment]
No big changes. Just add some methods to the subclass

**Comment by inhere** [comment]
@szepeviktor Thanks you.

**Comment by szepeviktor** [comment]
You're welcome.

Could you help me understand where SessionInterface::push() gets defined?
Thanks.

**Comment by inhere** [comment]
hi @szepeviktor 

The method `SessionInterface::push`, only use for websocket connection session.

such as:

https://github.com/swoft-cloud/swoft/blob/master/app/WebSocket/Test/TestController.php#L59-L96

If it is on a TCP server, there is no such method.

**Comment by szepeviktor** [comment]
@inhere All right, I see where it is used.
But where is it defined?

**Comment by inhere** [comment]
defined at https://github.com/swoft-cloud/swoft-component/blob/master/src/framework/src/Session/SessionInterface.php

**Comment by szepeviktor** [comment]
@inhere Thank you.
I see no `function push` in that file.

**Comment by inhere** [comment]
The interface only contains common method definitions.

**Comment by szepeviktor** [comment]
Oh ❕ 
Then we have a PHPDoc (or another) problem.

`function mustGet(string $sid = ''): SessionInterface`

If SessionInterface defines no push method, you may not call it.
Could you dig into this?

**Comment by inhere** [comment]
reutrn type is interface.

but return doc has contains subclass `@return SessionInterface|Connection`:

https://github.com/swoft-cloud/swoft-component/blob/d770cda75a86dbfd0f720955084b2c0a89bb78cc/src/framework/src/Session/Session.php#L98-L110


```php
    /**
     * Get session by FD
     *
     * @param string $sid If not specified, return the current corresponding session
     * @return SessionInterface|Connection
     */
    public static function get(string $sid = ''): ?SessionInterface
    {
        $sid = $sid ?: self::getBoundedSid();
        return self::$sessions[$sid] ?? null;
    }
```

**Comment by szepeviktor** [comment]
I see.
Trying to resolve contradiction between PHPDoc and return type in https://github.com/swoft-cloud/swoft-component/pull/513

**Comment by szepeviktor** [comment]
BTW As for the source of `mustGet()`: errors should go into if-s, normal execution should go without indentation. (now it is the opposite)

**Pull request merged**
